server.port=8998

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=true

spring.datasource.url=jdbc:h2:mem:vacancies_final_v20
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/master.yaml
spring.liquibase.enabled=true
